#!/usr/bin/env python3
import sys

if len(sys.argv) == 1: sys.exit(1)


import tty
import os
import termios
import itertools
import random
import requests


def alternating_size_chunks(iterable, steps):
    n = 0
    step = itertools.cycle(steps)
    while n < len(iterable):
        next_step = next(step)
        yield iterable[n:n + next_step]
        n += next_step
        
useUrl = False
useWrite = True

url = ""

for arg in sys.argv:
    if arg == "-u" or arg == "--url":
        useUrl = True
        useWrite = False
        url = sys.argv[2]
        break


file_content=""
if useUrl:
    file_content = requests.get(url).text
else:
    with open(
            os.path.expanduser( sys.argv[1] )
        ) as file:
        file_content = file.read()

start = 2
end = 5

content = list(alternating_size_chunks(file_content, (random.randrange(start, end), random.randrange(start, end), random.randrange(start, end))))



def speed_type():
    if len(content) == 0:
        sys.exit(0)
    print(content[0], end="", flush=True)
    del content[0]
def getkey():
    old_settings = termios.tcgetattr(sys.stdin)
    tty.setcbreak(sys.stdin.fileno())
    try:
        while True:
            b = os.read(sys.stdin.fileno(), 3).decode()
            if len(b) == 3:
                k = ord(b[2])
            else:
                k = ord(b)
            key_mapping = {
                27: 'esc'
            }
            return key_mapping.get(k, chr(k))
    finally:
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, old_settings)
try:
    while True:
        k = getkey()
        if k == 'esc':
            quit()
        else:
            speed_type()
except (KeyboardInterrupt, SystemExit):
#    os.system('stty sane')
#    print('stopping.')
    pass
